### ISSUE TITLE
Fix Markup Issues in index.html

### ISSUE THREAD

**Issue by krebedev** [DeeOkw/Project-E-Library#1]
The markup looks great, structurally and semantically. Here are a few issues I noticed:

1. Missing closing tag: The closing `>` character is missing in the last line of the markup.
2. Overlapping closing `</div>` on line 80: There's no corresponding opening tag for this. Please remove this.
3. Overlapping closing `</h2>` on line 248: There's no corresponding opening tag for this. Please remove this.
4. Missing closing `div`: Add a closing `</div>` tag before the closing `</section>` on line 327
5. Missing `alt` text in image tags: Images do not have `alt` texts/attributes. Read about this [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt).
6. Duplicate section ID: There are two sections with the same ID "recent." IDs should be unique within an HTML document. To resolve this issue, you can either change the ID of one of the sections or remove one of the sections if it's not necessary.

Note: To preserve the above line numbers, first comment out a line that needs to be deleted. When you've addressed all issues you can delete them.

If you don't already have the Prettier - Code formatter (VS Code extension) installed, go ahead and install it in VS Code. It helps catch many of these syntax errors.

**Comment by DeeOkw** [comment]
Thank you so so much sir for the comprehensive feedback. I really
appreciate it.
I am actually currently  working on this project. So I was duplicating &
deleting some codes as at where necessary. I am not yet done hopefully by
tomorrow but ild make the changes you suggested.
Thank you again.

**Comment by Anuj3366** [comment]
is this issue fixed?

**Comment by DeeOkw** [comment]
Yes it's all fixed now.

**Comment by Anuj3366** [comment]
i just find out its not so please assign me this issue
